version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-uiaweohgihsioJEPAWJpjijOJJRSIJGIPWEIoiniPEGJPOjPIejiapbrjnAIOWEIpwjegpIWEJ3JPIjBIREPI0H40IEH0IBO3NDINliHPiIp;zbzbf=zr-+_40jzinrpb
    command: >
      sh -c "
        python manage.py migrate --noinput &&
        python manage.py runserver 0.0.0.0:8000
      "