name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: 'django-insecure-uiaweohgihsioJEPAWJpjijOJJRSIJGIPWEIoiniPEGJPOjPIejiapbrjnAIOWEIpwjegpIWEJ3JPIjBIREPI0H40IEH0IBO3NDINliHPiIp;zbzbf=zr-+_40jzinrpb'
      DJANGO_SETTINGS_MODULE: 'config.settings.base'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
          pip install -r requirements/base.txt

      - name: Run ruff linter
        run: ruff check .

      - name: Run Django tests
        run: python manage.py test
